dist: xenial

sudo: false

services:
  - docker
  - postgresql

language: python

python:
  - '3.5'
  - '3.6'
  - '3.7'

before_install:
  - git clone https://github.com/plgitlogin/sandbox.git
  - cp test/config_test_pgsql.py premierlangage/config.py
  - pip3 psycopg2
  - cd sandbox/
  - ./install.sh
  - python3 manage.py runserver 7000 &> /dev/null &
  - cd ..
  - yes n | ./script/install_release.sh

install:
  - pip install -U wheel setuptools
  - pip install tox-travis
  - pip install codecov

script: tox

after_success: codecov

env:
  global:
    - PGPORT=5432