dist: xenial

sudo: false

services: docker

language: python

python:
  - '3.5'
  - '3.6'
  - '3.7'

before_install:
  - git clone https://github.com/plgitlogin/sandbox.git
  - cd sandbox/
  - ./install.sh
  - python3 manage.py runserver 7000 &
  - cd ..

install:
  - pip install -U wheel setuptools
  - pip install tox-travis
  - pip install codecov

script: tox

after_success: codecov
