site_name: Premier Langage
site_author: Q. Coumes, D. Revuz


nav:
- Home: 'index.md'
- Ecrire un exercice:
    - 'Bases': 'introduction.md'
    - 'Construction': 'construction.md'
    - 'Affichage / Formulaire': 'affichage.md'
    - 'Évaluation': 'evaluation.md'
    - "Ecrire une Feuille d'Exercices": 'pltp.md'
- Builders:
    - 'index': 'builder_index.md'
    - 'before': 'before.md'
    - 'build': 'build.md'
- Formulaires:
    - 'index': 'form_index.md'
- Graders:
    - 'index': 'grader_index.md'
    - 'evaluator': 'evaluator.md'
    - 'evalfunc': 'evalfunc.md'

theme:
    name: null
    custom_dir: 'custom'

site_dir: ../templates/documentation/doc
